"use client";
import { useState } from "react";
const questions = [
  ["What is Infinitswap?", "Infinitswap is a financial platform that helps you hold, convert and spend USDT and stablecoins in local currencies across Africa. It works entirely through WhatsApp — no app to download, no dashboard to learn. You can pay bills, buy airtime, cash out to your local bank account, save and earn rewards, all in one chat."],
  ["Is Infinitswap a bank?", "No. Infinitswap is a financial technology platform, not a bank. It connects you to regulated payment providers and licensed partners who handle the actual movement of funds. Infinitswap coordinates the experience; the licensed providers power the payments."],
  ["Who holds my funds?", "Your funds move through the licensed payment providers handling your specific transaction. Infinitswap does not hold your money in a proprietary ledger or act as a custodian of your funds."],
  ["Who provides the payment services?", "Payment services are provided by regulated partners licensed by the Central Banks of Nigeria, South Africa, Ghana and Tanzania. These partners handle the local currency side of every transaction."],
  ["What fees apply?", "Fees depend on the type of transaction and the countries involved. Before you confirm any transaction, Infinitswap shows you the full details — exchange rate, fee and the amount you will receive — so there are no surprises."],
  ["How does crypto-to-cash conversion work?", "You tell Infinitswap what you want to convert and how much. It gives you a live rate, which is locked for a short window. You confirm, send your USDT to the provided address, and your local currency is sent to your bank account or mobile money wallet."],
  ["How long do transactions normally take?", "Most transactions complete in seconds to a few minutes once your USDT is received on-chain. Actual timing depends on blockchain confirmation speed and the payment provider handling the local currency delivery."],
  ["What happens if a transaction fails?", "If a transaction cannot be completed, Infinitswap will notify you in the chat and initiate a reversal where applicable. Customer support is available at +234 907 960 7916 to help resolve any issue."],
  ["How is my information protected?", "Your WhatsApp conversation is protected by WhatsApp's end-to-end encryption. Infinitswap does not ask for or store your private keys or wallet recovery phrases. Never share these with anyone."],
  ["Which countries are currently supported?", "Infinitswap currently supports Nigeria, Ghana, Tanzania, South Africa, Rwanda, Uganda and Kenya. More countries are being added. Check infinitswap.ai for the most current list."],
  ["Can I spend USDT directly in Africa?", "In most everyday situations, merchants price goods in local currency, so you will need to convert first. Infinitswap makes that conversion fast and the resulting local currency immediately usable for payments, bills and transfers."],
  ["Can I convert USDT to Naira?", "Yes. USDT-to-Naira is one of the most common transactions on Infinitswap. Just tell the bot how much you want to convert, confirm the live rate, and your Naira lands in your bank account."],
  ["Can I use USDT to pay bills?", "Yes. Infinitswap supports bill payments including electricity, cable TV, internet and mobile airtime and data across supported countries. You can set up autopay for recurring bills too."],
  ["Is USDT the same as the US dollar?", "No. USDT is a digital stablecoin designed to track the value of the US dollar. It is not issued by a government or central bank. Tether, the issuer, maintains reserves to keep its value close to $1, but it is a separate digital asset, not legal tender."],
];
export default function FAQ() { const [active, setActive] = useState<number | null>(0); return <section id="faq" className="bg-[#F9F7FF] py-24 md:py-28"><div className="section-wrap"><h2 className="display mx-auto max-w-[760px] text-center text-[clamp(24px,3vw,40px)] font-bold tracking-[-.045em]">What you should know before you start.</h2><div className="mx-auto mt-12 max-w-[720px] divide-y divide-[#E8E0F7] border-y border-[#E8E0F7]">{questions.map(([question, answer], index) => <div key={question}><h3><button className="flex w-full items-center justify-between gap-4 py-5 text-left font-display text-[17px] font-semibold focus:outline-none focus-visible:ring-2 focus-visible:ring-[#6C3FE8]" aria-expanded={active === index} onClick={() => setActive(active === index ? null : index)}><span>{question}</span><span className="text-2xl font-normal text-[#6C3FE8]">{active === index ? "−" : "+"}</span></button></h3><div className={("faq-answer " + (active === index ? "faq-open" : ""))}><p className="pb-5 leading-[1.6] text-[#5A4E6E]">{answer}</p></div></div>)}</div></div></section>; }
